### ISSUE TITLE
I2C address is always default using the constructor

### ISSUE THREAD

**Issue by jr3cermak** [romainmp/MCP9808#2]
@romainmp - Please see this [post](https://community.particle.io/t/cant-read-multiple-mcp9808-sensors/34856/).  There are a couple recommendations on how to change the code a little bit to allow different I2C addresses to be set.  Thanks!  Rob

**Comment by ScruffR** [comment]
It would be an easy fix 
```
	_i2cAddr = (MCP9808_DEFAULT_ADDRESS & addr == MCP9808_DEFAULT_ADDRESS) ? addr : MCP9808_DEFAULT_ADDRESS;
```
should actually be
```
	_i2cAddr = ((MCP9808_DEFAULT_ADDRESS & addr) == MCP9808_DEFAULT_ADDRESS) ? addr : MCP9808_DEFAULT_ADDRESS;
```

The original code assumes a wrong order of execution but a conciously placed set of parentheses solves the issue.

**Comment by marekparticle** [comment]
@romainmp - the change above is a request Particle has seen several times. We are interested in potentially making this modification to the library on the Particle side - please let me know if you have any objections.

**Comment by romainmp** [comment]
Sorry about the delay.

**Comment by ScruffR** [comment]
Can you please also re-upload and publish the new version to the Particle library repository?

**Comment by romainmp** [comment]
Done, can you confirm it is OK on your side ?

**Comment by ScruffR** [comment]
Yup, all fine on my side :+1:
